export const TEMPLATES_COLLECTION_NAME = 'templates';
export const USERS_COLLECTION_NAME = 'users';
export const JOB_RETRY_LIMIT = 3;
export enum JOB_SERVICE_MESSAGE_PATTERNS {
  CREATE_JOB = 'CREATE_JOB',
  GET_JOB = 'GET_JOB',
  GET_JOB_CHANGELOG = 'GET_JOB_CHANGELOG',
}
